In [1]:
import numpy as np
import pandas as pd
data=[1,2,np.nan,4]
index_data=['a','b','c','d']
indexed_se=pd.Series(data,index_data)
print(indexed_se)

a    1.0
b    2.0
c    NaN
d    4.0
dtype: float64

In [13]:
from pandas import Series, DataFrame

daeshin = {
    'open':  [11650, 11100, 11200, 11100, 11000],
    'high':  [12100, 11800, 11200, 11100, 11150],
    'low':   [11600, 11050, 10900, 10950, 10900],
    'close': [11900, 11600, 11000, 11100, 11050]
}

daeshin_day = DataFrame(daeshin)
print(daeshin_day)

    open   high    low  close
0  11650  12100  11600  11900
1  11100  11800  11050  11600
2  11200  11200  10900  11000
3  11100  11100  10950  11100
4  11000  11150  10900  11050

In [12]:
import numpy as np
import pandas as pd
nparray1=np.array([[1,2,3],[4,5,6]])
dic={'a':[1,2,3,4],'b':[5,6,7,8],'c':[9,10,11,12]}
display(pd.DataFrame(dic))
display(pd.DataFrame(nparray1))

   a  b   c
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

   0  1  2
0  1  2  3
1  4  5  6

In [5]:
from pandas import Series,DataFrame
mine=Series([10,20,30],index=['naver','sk','kt'])
friend=Series([10,20,30],index=['kt','naver','sk'])

merge=mine+friend

print(DataFrame(merge,columns=['price']))

       price
kt        40
naver     30
sk        50